### ISSUE TITLE
Repository for JellyCon?

### ISSUE THREAD

**Issue by ltGuillaume** [mcarlton00/jellycon#12]
Is there a repository addon (in the making) for JellyCon, so updates can be done automatically?

E: Sorry for the bug label, my bad.

**Comment by TrueTechy** [comment]
Yes we will likely be adding it to the existing jellyfin repo.

Don't worry about the label, it's automatic when submitting an issue

**Comment by mcarlton00** [comment]
Techy is correct, it's going to be added to https://repo.jellyfin.org/releases/client/kodi/ at some point in the (hopefully) near future.  The repo has been going through an overhaul to allow both existing releases and the upcoming Kodi 19 release to function properly, so we just haven't gotten the time to add this to that repo as well yet during the shakeup.

**Comment by ltGuillaume** [comment]
That's great news, thanks for the quick response 🙂 I'll keep an eye out for updates to the repo, thanks!
