### ISSUE TITLE
"Play from beginning" resumes from previous position

### ISSUE THREAD

**Issue by ltGuillaume** [mcarlton00/jellycon#17]
**Describe the bug**
When choosing "Play from beginning" from the context menu, instead of doing so, the video still resumes from the last position. In comparision, this function works as expected for SMB shares.

**System (please complete the following information):**
 - OS: Raspberry Pi
 - Jellyfin Version: latest via linuxserver.io
 - Kodi Version: 18.8 (LibreELEC 9.2.4)
 - Addon Version: 0.2.0

**Comment by mcarlton00** [comment]
We recently had a similar issue in JF for Kodi.  Hopefully it's the same simple fix here, but I haven't been in that part of the code yet.  https://github.com/jellyfin/jellyfin-kodi/pull/346

**Comment by mcarlton00** [comment]
I actually can't replicate this.  I've tried against a few different movies and episodes of shows and it's been behaving as expected.

Have you checked the settings for the "Auto resume" feature to see if it's enabled?  JellyCon -> Add-on Actions -> Show Add-on Settings -> Events

**Comment by mcarlton00** [comment]
Sorry for the delay, finally got back to looking at this and I must be missing something.  When I select a movie when auto resume is enabled, it automatically plays from that location.  Even going through the context menu I don't see an option to forcibly start from the beginning.

**Comment by ltGuillaume** [comment]
Hmz, that's strange: it used to be there for sure (https://github.com/mcarlton00/jellycon/blob/69f3c7cb5da52c537b49f50557937cf815395468/resources/language/resource.language.en_gb/strings.po#L318), but with the latest commit it indeed is gone.

**Comment by mcarlton00** [comment]
I only get that dialog when 'Auto Resume' is turned off and after selecting play.  I've gone back to 0.2.0 and getting the same behavior.  I can see why it would make sense to include that as an option in the context menu though, especially if auto resume is turned on.

Also, it's still working fine on the movies that I tested.

**Comment by ltGuillaume** [comment]
This probably had to do with me turning off "Use JellyCon context menu".
