### ISSUE TITLE
Cannot connect to my jellyfin server "Invalid username or password entered"

### ISSUE THREAD

**Issue by Peobran** [mcarlton00/jellycon#36]
**Describe the bug**

Cannot connect to my jellyfin server. Always says "Invalid username or password entered"
It worked great before, but I had to fully reset my AndroidTV Box and reinstall Kodi and Jellycon. Then, now, it's not working anymore.
I just tried with Jellycon 0.2 and I can connect. So It is just with Jellycon 0.3 that it's not working.

**To Reproduce**

1. Install a new Kodi
2. Install Jellycon on Kodi
3. Enter the new server
4. Mannualy connect (Enter username then password)
5. See Error

**Expected behavior**

Connect to my jellyfin server.

**Logs**

[ERR] [82] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[INF] [82] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "xxxx" has been denied (IP: "xxxx.xxxx.xxxx.xxxx").
[ERR] [82] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Invalid username or password entered". URL: "http://xxxx.xxxx.xxxx.xxxx:xxxx/Users/AuthenticateByName?format=json"

**Screenshots**

**System (please complete the following information):**
 - OS: Android TV
 - Jellyfin Version: Version : 10.6.4
 - Kodi Version: 18.9 (tried in 18.5 too)
 - Addon Version: 0.3

**Additional context**

Thank very much for bringing us this amazing project.

**Comment by berndt-toast83** [comment]
I can concur on this issue, tried last night on version 0.3 could not connect, downgraded to 0.2 could connect just fine.

**Comment by mcarlton00** [comment]
I'm not able to replicate this on a 10.6.4 or a 10.7-rc1 server.  Can you collect logs when trying to login and see if any errors are thrown there?  https://kodi.wiki/view/Log_file/Easy

**Comment by berndt-toast83** [comment]
Here are the errors I see. I replicated this using Kodi for Windows 18.9 and JF server is 10.6.4, note this was originally found on my NVidia Shield TV running android, same errors:
https://pastebin.com/6Le0ffKu

**Comment by berndt-toast83** [comment]
I wonder if it has to do with the changes made to the message_data:
-       message_data = "username=" + user_name + "&pw=" + pwd_text
+      message_data = {'username': user_name, 'pw': pwd_text}

**Comment by mcarlton00** [comment]
Most likely related, but I don't understand why at this moment.  The old form based login method has been deprecated forever, and we should be using the json payload method.  It also doesn't explain why it's working fine on my system but not yours, unless android and windows are behaving different than linux.

Try enabling debug logging (Addons -> Video Addons -> JellyCon -> Addon Actions -> Show addon settings -> Advanced -> Enable debug logging), then restart Kodi and check your logs.  You should be able to find a section afterwards with your server info and the payload it sent to the server.  Should look something like this:

```
2020-12-17 18:34:00.981 T:139851760387648  NOTICE: JELLYFIN.resources.lib.downloadutils -> DEBUG::resources/lib/downloadutils.py:675 After: https://jellyfin.domain.com/User/AuthenticateByName?format=json
2020-12-17 18:34:00.982 T:139851760387648  NOTICE: JELLYFIN.resources.lib.downloadutils -> DEBUG::resources/lib/downloadutils.py:702 Content-Type: application/json
2020-12-17 18:34:00.982 T:139851760387648  NOTICE: JELLYFIN.resources.lib.downloadutils -> DEBUG::resources/lib/downloadutils.py:703 POST DATA: {"username": "matt", "pw": "my_secret_password"}
```

Verify that the POST DATA line is correct with your user/password.  (Don't post it here, obviously.  Just need confirmation that it's correct)

**Comment by berndt-toast83** [comment]
POST data looks accurate. However, the password for my user has an ! in it, and it is escaped as such in the JSON:
%21
Can we make sure that escaped characters work fine with this new method? Here is an example, not my actual credentials:
POST DATA: {"username": "test_name", "pw": "123ABC%21"}

**Comment by berndt-toast83** [comment]
That looks like HTML escaping, but JSON has different escaping needs:
https://www.freeformatter.com/json-escape.html#ad-output

**Comment by mcarlton00** [comment]
I doesn't need to be escaped at all, we can just give the request the raw json payload.  I just overlooked it when making the initial change to be 10.7 compatible

**Comment by berndt-toast83** [comment]
Excellent! I am a QAer at my company, so I'm glad to be able to use my talents elsewhere.

**Comment by berndt-toast83** [comment]
I also manually made the requested change in downloadutils.py in my Kodi addons folder, and I can confirm that it now logs me in correctly. Thanks for the quick fix!
