### ISSUE TITLE
Clone Default Skin not working

### ISSUE THREAD

**Issue by berndt-toast83** [mcarlton00/jellycon#38]
**Describe the bug**
Using the Clone Default Skin option fails.

**To Reproduce**
1. Go to Add-on Actions
2. Select Clone Default Skin
3. See error asking you to check Kodi log

**Expected behavior**
Default Estuary Skin should be cloned with added Jellyfin functionality.

**Logs**
https://pastebin.com/Yu70Nw9E

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.6.4
 - Kodi Version: 18.9
 - Addon Version: 0.3

**Comment by berndt-toast83** [comment]
Log with Debug logging enabled:
https://pastebin.com/fKALpi8p

**Comment by mcarlton00** [comment]
Not gonna lie, I didn't even realize this was an option in the addon.  Seems a bit hacky, but I also don't have a better method of doing it right now.   Should be an easy fix. Thanks for the logs.
