### ISSUE TITLE
Kodi 19/Python 3 Support

### ISSUE THREAD

**Issue by mcarlton00** [mcarlton00/jellycon#4]
Need to translate the code to run properly on both Python 2 and 3.  Will likely need both `script.module.six` (urllib and string processing) and `script.module.kodi-six` (kodi specific modules) for the translation layer.

**Comment by spec1re** [comment]
Any news on this? Using Kodi 19 Beta 1/2 now for a while and it works very well here, would like to try this addon.

**Comment by mcarlton00** [comment]
Nothing yet unfortunately, I just haven't had enough time to look into what all changes are needed.  I should have some time over the next few weeks during the holidays, but we'll see what happens.  I believe the Kodi Matrix release is rumored to be releasing first quarter of 2021, so it definitely needs to be looked into soon.

**Comment by mcarlton00** [comment]
Just because I know people are watching this: I've been working on the py3 conversation on and off for the last few days.  I've gotten that addon running and browsing and most functionality seems to be working correctly, but playback is silently failing.  So it's not ready yet, but it's getting closer.

**Comment by mcarlton00** [comment]
Update: playback is working, but playback reporting and the image cache system is not.  Slowly getting there
