### ISSUE TITLE
invalid username or password

### ISSUE THREAD

**Issue by Ulrar** [mcarlton00/jellycon#51]
**Describe the bug**
Using Kodi on an nvidia shield, following yesterday's upgrade to kodi 19 the plugin was broken like for many users.
I've reinstalled the app hoping that would fix it, but now trying to reconfigure the plugin I'm failing to log in, always getting "Invalid username or password".
It was working fine on kodi 18 yesterday.

I've seen other issues mentioning the hashing algorithm changed in jellyfin, but they were resolved as I understand it ?

I've also had to copy the repository.jellyfin.kodi.zip by usb from my desktop as the usual method of adding kodi.jellyfin.org as a source did not show that file for some reason.

**To Reproduce**
Reinstall the plugin from scratch on kodi 19 and try to log in

**Expected behavior**
Be able to login

**System (please complete the following information):**
 - OS: Android (nvidia shield pro)
 - Jellyfin Version: Docker Linuxserver/jellyfin:nightly
 - Kodi Version: 19
 - Addon Version: 0.7.0-py3

**Additional context**

**Comment by mcarlton00** [comment]
Are you using Jellyfin for Kodi, or JellyCon?  They're two entirely different addons, and this is the repo for JellyCon.  I don't have a published release for Kodi 19 compatibility yet, but most of the work has been completed in #50.

**Comment by Ulrar** [comment]
Apologies, I didn't realize there were two addons. I'm not sure how I even ended up here since I didn't know Jellycon existed, sorry about the noise.
But if it doesn't depend on synchronizing the database locally then it sounds very interesting, I'll definitely give it a try when Kodi 19 gets support.
